#!/bin/bash

SS=~/workspace/ss/
IMG=~/workspace/image/
LOG=~/workspace/image/out/s2e-last/messages.txt
OUT=~/workspace/image/out/test.txt

LEVEL=3

LIST=(
  'false'
  'true'
  'echo ${PATH}'

  'touch file'
  'chgrp root file'
  'chown root file'
  'chmod +rwx file'
  'cp file copy'
  'mv file moved'
  'rm file'
  'ln -s file link'
  'readlink file'
  'mkdir dir2'
  'rmdir dir'
  'mknod fifo p'
  'mkfifo fifo'
  'mktemp'
  'dd if=/dev/urandom of=file bs=512 count=1'

  'cat /proc/self/maps'
  'stat /proc/self/maps'
  'head /proc/self/maps'
  'tail /proc/self/maps'
  'nl /proc/self/maps'
  'sort /proc/self/maps'
  'od /proc/self/maps'

  'basename /proc/self/maps'
  'dirname /proc/self/maps'

  'base64 /proc/version'
  'sum /proc/version'
  'cksum /proc/version'
  'md5sum /proc/version'
  'sha1sum /proc/version'
  'sha224sum /proc/version'
  'sha256sum /proc/version'
  'sha384sum /proc/version'
  'sha512sum /proc/version'

  'ls'
  'dir'
  'vdir'

  'sleep 1'
  'stty -F /dev/tty'
  'sync'

  'du /tmp'
  'df /tmp'

  'factor 15'
  'seq 1 10'

  'date'
  'env'
  'printenv'
  'uname'
  'nproc'

  'id'
  'groups'
  'users'  
  'who'
  'whoami'
  )

cp ${IMG}/script.sh /tmp/
cp ${IMG}/config.lua /tmp/

truncate -s 0 ${OUT}

for elem in "${LIST[@]}"
do
   echo "Testing ${elem}"

   binary="/root/cu-O${LEVEL}/src/${elem}"

   sed -e "s#BINARY#${binary}#g" > ${IMG}/config.lua <<-EOF
	s2e = {}
	plugins = {
	   "BaseInstructions",
	   "HostFiles",
	   "LinuxMonitor",
	   "ModuleExecutionDetector",
	   "StackMonitor",
	   "MemSafety"
	}
	pluginsConfig = {}
	pluginsConfig.HostFiles = {
	   baseDirs = {"/home/ptt/workspace/image"}
	}
	pluginsConfig.ModuleExecutionDetector = {
	   somename = {
	      moduleName = "BINARY",
	      kernelMode = false
	   }
	}
	EOF

   sed -e "s#BINARY#${binary}#g" > ${IMG}/script.sh <<-EOF
	#!/bin/sh
	./s2eget memsafety.so
	S2E=1 LD_PRELOAD=./memsafety.so BINARY
	./s2ecmd kill 0 "DONE"
	EOF

   ${SS}/run-s2e --novnc

   errcnt1=-1
   errcnt2=-1
   if grep 'LinuxMonitor: Unloaded module' ${LOG} > /dev/null; then
      errcnt1=$( grep 'MemSafety: Unbounded' ${LOG} | wc -l )
      errcnt2=$( grep 'MemSafety: Unbounded' ${LOG} | grep -v 'write to .*: 0x8 above stack bound' | wc -l )
   fi

   echo "Result: ${errcnt2} ${errcnt1}"
   echo

   printf "%6i %6i %s\n" "${errcnt2}" "${errcnt1}" "${elem}" >> ${OUT}
done

mv /tmp/script.sh ${IMG}/
mv /tmp/config.lua ${IMG}/

echo "---"
sort -r -h ${OUT} -o ${OUT}
cat ${OUT}

