#!/bin/bash

set -e -u
set -o pipefail

BIN=~/workspace/image/bin
LOGDIR=~/workspace/image/out/s2e-last

[ $# -eq 1 ] && LOGDIR=$1

LOG=${LOGDIR}/messages.txt
PCOUT=${LOGDIR}/pcs.txt
FOUT=${LOGDIR}/funcs.txt

# Args: file
get_load_addr()
{
	line=$(grep 'r-xp' ${LOG} | grep ${1} | tail -n 1)
	[ -z "${line}" ] && return 0

	words=(${line})

	addr=${words[7]}
	addr=${addr%-*}
	addr="0x${addr}"

	echo $addr
}

# Args: file offset
get_func_name()
{
	out=$(addr2line -f -e ${BIN}/${1} ${2} 2>/dev/null | tr '\n' ' ')
	[ -z "${out}" ] && return 0

	out=(${out})
	func=${out[0]}
	line=${out[1]##*/}

	echo "${func} ${line}"
}

truncate -s 0 ${PCOUT}
truncate -s 0 ${FOUT}

echo 'Making list of PCs'

LOGSIZE=$(stat -c %s ${LOG})
cat ${LOG} \
	| pv -p -w 32 -s ${LOGSIZE} \
	| grep 'MemSafety: Unbounded' \
	| grep -v 'write to .*: 0x8 above stack bound' \
	| awk '{print $7, $9}' \
	| sort \
	| uniq -c \
	| sort -h -r \
	> ${PCOUT}

echo 'Making list of functions'

PCCNT=$(wc -l < ${PCOUT})

declare -A LDADDR
FCNT=0

while read -r line; do
	words=(${line})

	cnt=${words[0]}
	addr=${words[1]}
	file=${words[2]}
	file=${file#*\'}
	file=${file%\'*}
	file=${file#*:}

	set +u
	has_ldaddr='yes'
	[ -v ${LDADDR[${file}]} ] && has_ldaddr='no'
	set -u

	if [ ${has_ldaddr} = 'no' ]; then
		ldfile=${file}
		[ ${file} = 'libdl.so.2' ] && ldfile='libdl-2.13.so'
		[ ${file} = 'libc.so.6' ] && ldfile='libc-2.13.so'
		LDADDR[${file}]=$(get_load_addr ${ldfile})
		if [ -z "${LDADDR[${file}]}" ]; then
			echo Failed to get load addr for ${file}
			exit 1
		fi
	fi

	offset=$(printf '0x%x' $((${addr} - ${LDADDR[${file}]})))

	func=$(get_func_name ${file} ${offset})
	if [ -z "${func}" ]; then
		func='???'
		line='???'
	else
		func=(${func})
		line=${func[1]}
		func=${func[0]}
	fi

	printf '%6i %20s %-20s %20s (PC %s offset %s)\n' \
		${cnt} ${file} "${func}" "${line}" ${addr} ${offset} >> ${FOUT}

	chars=$(( ( ${FCNT} + 1 ) * 25 / ${PCCNT} ))
	spaces=$(( 25 - ${chars} ))
	cstr=$(printf "%${chars}s")
	sstr=$(printf "%${spaces}s")
	echo -en "\r[${cstr// /.}${sstr}] "
	FCNT=$(( ${FCNT} + 1 ))
done < ${PCOUT}
echo

sort -h -r ${FOUT} -o ${FOUT}

echo "---"
head -n 25 ${FOUT}

