#!/bin/bash
#
# Usage:
#   rcompile OPTIONS
# Options:
#   -l S2E_PATH    s2e source folder
#   -h HOST_NAME   host name
#   -r S2E_PATH    s2e source folder on host
#   -b BUILD_PATH  build folder on host
# Example:
#   rcompile -l ~/workspace/s2e -h vader1 -r '~/workspace/s2e' -b '~/workspace/build'
#

set -e -u

#
#
#

OPTIND=1
while getopts "l:h:r:b:" opt; do
  case "$opt" in
    l)
      LOCAL_S2E=${OPTARG}
      ;;
    h)
      REMOTE_HOST=${OPTARG}
      ;;
    r)
      REMOTE_S2E=${OPTARG}
      ;;
    b)
      REMOTE_BUILD=${OPTARG}
      ;;
   esac
done
shift $((OPTIND-1))

#
#
#

rsync -avz --exclude='.*' ${LOCAL_S2E}/ ${REMOTE_HOST}:${REMOTE_S2E}

CMD="
if [ ! -d ${REMOTE_BUILD} ]; then
  mkdir -p ${REMOTE_BUILD} &&
  cd ${REMOTE_BUILD} &&
  make -f ${REMOTE_S2E}/Makefile;
else
  export CPLUS_INCLUDE_PATH=/usr/include:/usr/include/x86_64-linux-gnu:/usr/include/x86_64-linux-gnu/c++/4.8 &&
  make -j16 -C ${REMOTE_BUILD}/qemu-release &&
  make -j16 -C ${REMOTE_BUILD}/guest-tools32 &&
  make -j16 -C ${REMOTE_BUILD}/guest-tools64;
fi
"

# Expand paths for sed
LOCAL_S2E=$(echo ${LOCAL_S2E})
REMOTE_S2E=$(ssh ${REMOTE_HOST} echo ${REMOTE_S2E})

ssh ${REMOTE_HOST} ${CMD} 2>&1 | sed -l "s#${REMOTE_S2E}#${LOCAL_S2E}#g"

