#!/usr/bin/expect -f
#
# Usage:
#   rmon HOST COMMAND
# Example:
#   rmon dslab-vader1.epfl.ch savevm
#   rmon dslab-vader1.epfl.ch quit
#

set host [lindex $argv 0]
set cmd  [lrange $argv 1 end]

set send_slow {1 .01}

log_user 0
spawn telnet $host 4444

expect { 
   "(qemu) "
}
send -s "$cmd\n\n"

