#!/bin/bash

set -e -u

IMAGE="${HOME}/workspace/image/image.s2e"
CONFIG="${HOME}/workspace/image/config.lua"
BUILD="${HOME}/workspace/build/"
RUNDIR="/tmp/x86_64-s2e-softmmu/"
OUT="${HOME}/workspace/image/out/"
VNCOPT='-vnc :0'

killvnc()
{
   kill ${VNCPID} 2>/dev/null
}

if [ "$#" -ge 1 ]; then
   if [ "$1" == '--novnc' ]; then
      shift
      VNCOPT=''
   fi
fi

rm -rf ${RUNDIR} > /dev/null
mkdir  ${RUNDIR}

cp    ${BUILD}/qemu-release/x86_64-s2e-softmmu/qemu-system-x86_64 ${RUNDIR}
ln -s ${BUILD}/qemu-release/x86_64-s2e-softmmu/op_helper.bc     ${RUNDIR}
ln -s ${BUILD}/opt/share/qemu/*                               ${RUNDIR}
sudo setcap CAP_NET_ADMIN=ep ${RUNDIR}/qemu-system-x86_64

if [ ! -z "${VNCOPT}" ]; then
   bash -c 'sleep 8; ssvncviewer -scale 1.5 :0 2>/dev/null' &
   VNCPID=$!
   trap killvnc INT EXIT
fi

cd ${OUT}

cat > /tmp/gdb.cfg << EOF
handle SIG38 noprint
run
EOF

#sudo gdb -x /tmp/gdb.cfg --args \
${RUNDIR}/qemu-system-x86_64 \
   -L ${RUNDIR} \
   ${IMAGE} \
   -m 128M \
   ${VNCOPT} \
   -net nic,model=e1000 -net tap \
   -loadvm 1 \
   -s2e-config-file ${CONFIG} \
   $@

