#!/bin/bash

RUN=/tmp/i386-softmmu

rm -rf ${RUN} > /dev/null
mkdir  ${RUN}
cp    ~/workspace/s2e/build/qemu-release/i386-softmmu/qemu-system-i386 ${RUN}
ln -s ~/workspace/s2e/build/opt/share/qemu/*                           ${RUN}
sudo setcap CAP_NET_ADMIN=ep ${RUN}/qemu-system-i386

${RUN}/qemu-system-i386 \
   ~/workspace/image/image.s2e \
   -m 96M \
   -net nic,model=e1000 -net tap \
   -monitor telnet:localhost:4444,server,nowait

