#!/bin/bash

set -e -u

IMAGE="${HOME}/workspace/image/image.s2e"
BUILD="${HOME}/workspace/build/"
RUNDIR="/tmp/x86_64-softmmu/"

rm -rf ${RUNDIR} > /dev/null
mkdir  ${RUNDIR}

cp    ${BUILD}/qemu-release/x86_64-softmmu/qemu-system-x86_64 ${RUNDIR}
ln -s ${BUILD}/opt/share/qemu/*                           ${RUNDIR}
sudo setcap CAP_NET_ADMIN=ep ${RUNDIR}/qemu-system-x86_64

${RUNDIR}/qemu-system-x86_64 \
   ${IMAGE} \
   -m 128M \
   -net nic -net tap \
   -monitor telnet:localhost:4444,server,nowait \
   $@

